version: '3'

services:
  gb_postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=gobarber
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - TZ=GMT
    volumes:
      - './dockerdatabases/postgres:/var/lib/postgresql/data'
    ports:
      - 5432:5432

  gb_redis:
    image: redis:alpine
    ports:
      - 6379:6379
